name: 'data_playground'
version: '1.0.0'
config-version: 2

profile: 'data_playground'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_playground:
    materialized: view
    staging:
      materialized: view
    marts:
      materialized: table
