dbt_project:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: admin
      password: ""
      catalog: iceberg
      schema: public
      host: trino
      port: 8080
      http_scheme: http
      threads: 4

    shop:
      type: postgres
      host: postgres
      user: admin
      password: password
      port: 5432
      dbname: shop
      schema: public
      threads: 4
